import type { ProductPage } from '../_lib/types';

export const applicantTrackingSystem: ProductPage = {
  slug: 'applicant-tracking-system',
  product: 'Applicant Tracking System',
  heroIcon: 'briefcase',
  publishedAt: '2026-05-03',
  updatedAt: '2026-05-03',

  meta: {
    title:
      'Applicant Tracking System for Resume Screening & Candidate Tracking | HireSort',
    description:
      'HireSort is a lightweight applicant tracking system for recruiters, founders, and hiring teams. Store resumes, screen candidates with AI, track stages, and reuse candidate profiles across roles.',
    keywords: [
      'applicant tracking system',
      'ATS software',
      'applicant tracking software',
      'lightweight ATS',
      'AI ATS',
      'resume management software',
      'candidate tracking software',
      'resume screening software',
    ],
    ogImage: '/logo.png',
    ogImageAlt: 'HireSort — lightweight applicant tracking system',
  },

  hero: {
    eyebrow: 'Applicant Tracking System',
    titlePrefix: 'Applicant tracking system ',
    titleAccent: 'built around resume screening.',
    lead: [
      'HireSort helps recruiters and hiring teams move from scattered resumes and spreadsheet tracking to a simple, AI-powered applicant tracking workflow. Store resumes in one place, screen candidates against job-specific rubrics, track hiring stages, and reuse candidate profiles across future roles.',
    ],
    primary: { label: 'Get started for free', href: '/#pricing' },
    secondary: { label: 'See how HireSort works', href: '#how-it-works' },
    supporting:
      'A lightweight ATS for teams that need faster shortlisting, cleaner candidate tracking, and less manual resume management — without the complexity of enterprise hiring software.',
  },

  sections: [
    {
      type: 'problem',
      eyebrow: 'The problem',
      title: 'Spreadsheets break when hiring starts moving.',
      intro:
        'Early hiring often starts with email, folders, and spreadsheets. That works for a while — until applications increase, multiple roles open, and recruiters need to remember who was screened, shortlisted, rejected, or worth revisiting later.',
      bullets: [
        'Resumes scattered across jobs, folders, and inboxes',
        'No central candidate repository',
        'Manual resume screening for every new role',
        'Candidate stages tracked in spreadsheets',
        'No easy way to reuse past resumes',
        'Hiring managers receiving inconsistent shortlists',
        'Weak visibility into candidate history across roles',
      ],
      closing:
        'HireSort solves this by combining AI resume screening with lightweight applicant tracking.',
    },
    {
      type: 'positioning',
      eyebrow: 'Positioning',
      title: 'More than a screening tool. Simpler than a full ATS.',
      body: [
        'HireSort is designed for recruiters, founders, hiring managers, and agencies that need practical applicant tracking without heavy implementation. It gives you the core workflow most small and growing teams actually need.',
      ],
      flow: [
        'Create job',
        'Upload resumes',
        'Build candidate repository',
        'Screen with AI',
        'Rank candidates',
        'Track stages',
        'Reuse resumes',
      ],
      closing:
        'HireSort is not trying to replace every enterprise ATS workflow from day one. Instead, it focuses on the most painful part of hiring: turning resume volume into a structured, reusable candidate pipeline.',
    },
    {
      type: 'workflow',
      eyebrow: 'Core workflow',
      title: 'How HireSort works',
      intro:
        'A rubric-first, explainable workflow that ranks candidates against job-specific criteria — not blunt keyword matching.',
      steps: [
        { n: '01', title: 'Create a job', body: 'Paste or upload a JD. HireSort prepares the screening workflow around it.' },
        { n: '02', title: 'Generate a role-specific rubric', body: 'A structured scoring rubric is generated from the JD. Recruiters can review and edit before resumes are scored.' },
        { n: '03', title: 'Upload resumes', body: 'Drop in PDFs or DOCX. HireSort parses each candidate and stores it in your workspace.' },
        { n: '04', title: 'Build a central repository', body: 'Every uploaded resume becomes a structured candidate record with metadata, role link, score, and stage.' },
        { n: '05', title: 'Screen and rank candidates', body: 'Candidates are scored against the rubric with score breakdowns, strengths, gaps, and evidence.' },
        { n: '06', title: 'Track candidate stages', body: 'Move candidates across New, Shortlisted, Round 1/2, Offer, Hired, Rejected, or On Hold — per role.' },
        { n: '07', title: 'Reuse for future roles', body: 'Pull existing candidate records into new screenings instead of re-uploading the same resumes.' },
      ],
    },
    {
      type: 'features',
      eyebrow: 'Features',
      title: 'Applicant tracking features built for practical hiring.',
      intro:
        'Everything you need to turn resume volume into a clean, ranked, reusable candidate pipeline.',
      items: [
        { icon: 'database', title: 'Central resume repository', body: 'All uploaded resumes in one searchable candidate library — details, roles, scores, and stages in one place.' },
        { icon: 'tags', title: 'Candidate metadata extraction', body: 'Capture name, email, phone, current role and company, key skills, and years of experience automatically.' },
        { icon: 'layers', title: 'Resume-to-role association', body: 'Map every candidate to the JD they were considered for. Candidates can connect to multiple roles over time.' },
        { icon: 'sparkles', title: 'AI resume screening', body: 'Score candidates against job-specific criteria generated from the JD — not blunt keyword matching.' },
        { icon: 'listChecks', title: 'Ranked shortlists', body: 'Review candidates by score, rank, tier, and role fit instead of comparing every resume by hand.' },
        { icon: 'fileText', title: 'Candidate detail view', body: 'Resume preview, parsed metadata, role association, latest score, and current hiring stage in one view.' },
        { icon: 'ganttChart', title: 'Stage tracking', body: 'Move candidates through your hiring funnel with simple stage dropdowns — per candidate, per role.' },
        { icon: 'workflow', title: 'Funnel customization', body: 'Rename, add, remove, or reorder stages so the funnel matches how your team actually hires.' },
        { icon: 'filter', title: 'Search and filters', body: 'Find candidates by name, role, stage, score range, or date added.' },
        { icon: 'refreshCcw', title: 'Resume reuse', body: 'Reuse stored resumes across future roles so your candidate database compounds in value.' },
      ],
    },
    {
      type: 'fieldList',
      eyebrow: 'Candidate repository',
      title: 'Turn every resume into a reusable candidate record.',
      intro:
        'Most screening tools treat every upload as a one-time event. HireSort is moving toward a candidate-first model — every uploaded resume becomes a structured candidate record so your team can build a living candidate database rather than starting from zero for every new role.',
      cardLabel: 'Candidate record',
      cardIcon: 'userSearch',
      fields: [
        'Candidate name',
        'Email and phone number',
        'Current role and company',
        'Key skills',
        'Years of experience',
        'Date added',
        'Source of upload',
        'Role or JD association',
        'Latest AI screening score',
        'Current hiring stage',
      ],
    },
    {
      type: 'stages',
      eyebrow: 'Stage tracking',
      title: 'Track what happens after screening.',
      intro:
        'Screening is only the first step. Recruiters also need to know what happened next. HireSort tracks candidate movement across the full hiring funnel — per candidate, per role.',
      items: ['New', 'Shortlisted', 'Round 1', 'Round 2', 'Round 3', 'Offer Made', 'Hired', 'Rejected', 'On Hold'],
      closing:
        'Because stage is tracked per candidate per role, the same person can be rejected for one role, shortlisted for another, and kept on hold for a future opportunity.',
    },
    {
      type: 'plansSplit',
      eyebrow: 'Plans',
      title: 'Simple for individual recruiters. Powerful for growing teams.',
      free: {
        label: 'Free / MVP',
        heading: 'Genuinely useful for day-to-day recruiting.',
        bullets: [
          'Central resume repository',
          'Candidate metadata extraction',
          'Resume-to-role association',
          'Reuse of resumes for future screening',
          'Basic search and filtering',
          'Manual stage movement',
          'Basic funnel customization',
          'Candidate detail page with score and stage',
        ],
      },
      paid: {
        label: 'Paid / Expanded',
        heading: 'Built for deeper hiring operations.',
        bullets: [
          'Saved talent pools',
          'Saved filters and saved searches',
          'Advanced filtering combinations',
          'CSV export of candidates with stage, role, and score',
          'Candidate notes and recruiter comments',
          'Collaboration workflows',
          'Richer candidate history across multiple roles',
          'Advanced repository search',
          'Custom candidate table columns',
          'Kanban board view',
          'Bulk stage movement',
          'Multiple funnel templates',
        ],
      },
    },
    {
      type: 'useCases',
      eyebrow: 'Use cases',
      title: 'Built for teams that need structure without heavy ATS complexity.',
      items: [
        { icon: 'rocket', title: 'For startup recruiters', body: 'Manage 50–150 resumes per role without juggling spreadsheets, folders, and manual status updates.' },
        { icon: 'building', title: 'For founders', body: 'Hire your first team members with a structured process — even before you build a full HR function.' },
        { icon: 'users', title: 'For hiring managers', body: 'Define what matters for the role, review ranked candidates, and see why each was shortlisted.' },
        { icon: 'handCoins', title: 'For recruitment agencies', body: 'Manage high-volume resume pools, track candidates by role, and reuse strong profiles across clients.' },
      ],
    },
    {
      type: 'comparison',
      eyebrow: 'Comparison',
      title: 'HireSort vs traditional ATS software.',
      columns: ['Capability', 'Traditional ATS', 'HireSort'],
      accentColIndex: 2,
      rows: [
        ['Candidate database', 'Yes', 'Yes'],
        ['Resume repository', 'Yes', 'Yes — candidate-first and reusable'],
        ['Resume screening', 'Often manual or keyword-based', 'AI-assisted and rubric-based'],
        ['Candidate ranking', 'Limited or add-on', 'Built into screening workflow'],
        ['Candidate stage tracking', 'Yes', 'Lightweight stage tracking'],
        ['Funnel customization', 'Yes', 'Simple default funnel customization'],
        ['Resume reuse across roles', 'Varies', 'Core workflow'],
        ['Candidate detail view', 'Yes', 'Resume + metadata + score + stage'],
        ['Notes / comments', 'Usually yes', 'Paid / expanded workflow'],
        ['Kanban pipeline', 'Usually yes', 'Paid / expanded workflow'],
        ['Bulk actions', 'Usually yes', 'Paid / expanded workflow'],
        ['Interview scheduling', 'Often yes', 'Not in near-term scope'],
        ['Offer workflows', 'Often yes', 'Not in near-term scope'],
        [
          'Best fit',
          'Mature hiring operations',
          'Recruiters, founders, agencies, and growing teams that need screening-first applicant tracking',
        ],
      ],
    },
    {
      type: 'why',
      eyebrow: 'Why HireSort',
      title: 'Why choose a screening-first ATS?',
      items: [
        { title: 'Faster first-pass review', body: 'Move from hours of manual resume reading to structured shortlists.' },
        { title: 'Better candidate visibility', body: 'Keep resumes searchable and reusable instead of buried in old jobs or folders.' },
        { title: 'More consistent evaluation', body: 'Use job-specific rubrics instead of inconsistent manual judgment.' },
        { title: 'Cleaner candidate tracking', body: 'Track who is new, shortlisted, in interviews, rejected, hired, or on hold.' },
        { title: 'Less spreadsheet dependency', body: 'Replace scattered candidate trackers with one lightweight workspace.' },
        { title: 'Better repeat usage', body: 'As your repository grows, HireSort becomes more valuable for future roles.' },
      ],
    },
    {
      type: 'scope',
      eyebrow: 'Scope clarity',
      title: 'What HireSort is — and what it is not.',
      inLabel: 'In scope',
      inItems: [
        'Resume storage',
        'Candidate metadata',
        'AI screening',
        'Ranked shortlists',
        'Candidate stages',
        'Resume reuse',
        'Simple funnel tracking',
      ],
      outLabel: 'Not in near-term scope',
      outItems: [
        'Interview scheduling',
        'Offer letters',
        'Candidate messaging',
        'Background checks',
        'Onboarding',
        'Full CRM-style nurturing',
      ],
    },
  ],

  cta: {
    eyebrow: 'Ready when you are',
    title: 'Ready to replace spreadsheet-based applicant tracking?',
    body: 'Use HireSort to store resumes, screen candidates, track hiring stages, and build reusable candidate records.',
    primary: { label: 'Get started for free', href: '/#pricing' },
    secondary: { label: 'View pricing', href: '/#pricing' },
  },

  faqs: [
    { id: 'what-is-ats', question: 'What is an applicant tracking system?', answer: ['An applicant tracking system, or ATS, is software that helps hiring teams manage candidates through the hiring process. It typically includes resume storage, candidate profiles, application tracking, stage movement, search, filtering, and reporting.'] },
    { id: 'is-hiresort-an-ats', question: 'Is HireSort an ATS?', answer: ['HireSort is a lightweight applicant tracking system focused on resume screening, candidate management, and basic stage tracking. It is built for teams that want structure without the complexity of a full enterprise ATS.'] },
    { id: 'difference-from-traditional', question: 'How is HireSort different from a traditional ATS?', answer: ['Traditional ATS platforms often focus on full recruiting operations. HireSort focuses on the highest-friction part of hiring: resume management, AI screening, ranked shortlists, and simple candidate tracking.'] },
    { id: 'resume-repository', question: 'Does HireSort include a resume repository?', answer: ['Yes. The planned resume management layer includes a central resume repository where uploaded resumes are stored as reusable candidate records.'] },
    { id: 'multi-role-tracking', question: 'Can candidates be tracked across multiple roles?', answer: ['Yes. Candidate stage tracking is per candidate per role, which means the same candidate can have different statuses across different jobs.'] },
    { id: 'customize-stages', question: 'Can I customize hiring stages?', answer: ['Yes. The MVP includes basic funnel customization, including renaming stages, adding stages, removing unused stages, reordering stages, and defining one default funnel.'] },
    { id: 'kanban-bulk', question: 'Does HireSort include Kanban boards and bulk actions?', answer: ['These are part of the expanded paid workflow, not the free MVP. The MVP stays table-driven and simple.'] },
    { id: 'export', question: 'Can I export candidate data?', answer: ['CSV export is planned as part of the paid/expanded resume repository.'] },
    { id: 'startups', question: 'Is HireSort good for startups?', answer: ['Yes. HireSort is especially suitable for startups, small teams, solo recruiters, and agencies that need structure and speed but do not want heavy ATS implementation.'] },
    { id: 'replace-enterprise', question: 'Does HireSort replace enterprise ATS platforms?', answer: ['Not for every use case. HireSort is best positioned as a screening-first, lightweight ATS. It may not replace enterprise ATS platforms that require full interview scheduling, offer management, candidate communication, background checks, and onboarding workflows.'] },
  ],

  internalLinks: [
    { href: '/resume-screening-software', label: 'Resume Screening Software' },
    { href: '/resume-management', label: 'Resume Management' },
    { href: '/candidate-pipeline', label: 'Candidate Pipeline' },
    { href: '/recruitment-software', label: 'Recruitment Software' },
    { href: '/resources/compare/workable-alternative', label: 'Workable Alternative' },
    { href: '/#pricing', label: 'Pricing' },
  ],
};
