import type { ProductPage } from '../_lib/types';
import redirectURL from '@/lib/mainsSiteRedirectUrl';

export const recruitmentSoftware: ProductPage = {
  slug: 'recruitment-software',
  product: 'Recruitment Software',
  heroIcon: 'workflow',
  publishedAt: '2026-05-03',
  updatedAt: '2026-05-16',

  meta: {
    title: 'AI Recruitment Software for Resume Screening in 2026 | HireSort',
    description:
      'HireSort is AI recruitment software for resume screening, candidate shortlisting, and high-volume hiring. Replace spreadsheets with explainable AI scores, ranked shortlists, and lightweight candidate tracking.',
    keywords: [
      'recruitment software',
      'recruiting software',
      'hiring software',
      'recruitment management software',
      'AI recruitment software',
      'recruitment software for startups',
      'recruitment and hiring software',
      'recruiting platform',
      'candidate screening software',
      'recruitment screening software',
      'hiring manager software',
      'high-volume hiring software',
      'AI recruitment software for resume screening',
      'candidate shortlisting software',
      'recruitment software for high-volume hiring',
      'recruitment software for staffing agencies',
      'recruitment software for US hiring teams',
    ],
    ogImage: '/logo.png',
    ogImageAlt: 'HireSort — recruitment software for faster resume screening',
  },

  hero: {
    eyebrow: 'Recruitment software',
    titlePrefix: 'AI recruitment software ',
    titleAccent: 'built for resume screening and shortlisting.',
    lead: [
      'HireSort helps recruiters, founders, and hiring managers move from scattered resumes, manual screening, and spreadsheet tracking to a faster, more structured hiring workflow.',
      'Upload resumes, screen candidates with AI, review ranked shortlists, and track candidate progress from one simple recruitment workspace.',
    ],
    primary: { label: 'Get started for free', href: redirectURL },
    secondary: { label: 'See how it works', href: '#how-it-works' },
    supporting:
      'A lightweight recruitment screening software platform for teams that want faster shortlisting, cleaner candidate management, and less manual hiring work without the complexity of enterprise recruiting systems.',
  },

  sections: [
    {
      type: 'problem',
      eyebrow: 'The problem',
      title: 'Hiring Slows Down When Everything Lives in Different Places.',
      intro:
        'Recruiting often starts simply: resumes in email, candidate notes in spreadsheets, job descriptions in docs, and hiring feedback in chats. That works until hiring volume increases. Then teams start facing the same problems:',
      bullets: [
        'Resumes are scattered across inboxes, folders, and job posts',
        'Recruiters spend hours doing first-pass screening',
        'Hiring managers receive inconsistent shortlists',
        'Candidate status is manually tracked in spreadsheets',
        'Past resumes are forgotten instead of reused',
        'Screening decisions are difficult to explain',
        'Teams lose time deciding who should be reviewed next',
      ],
      closing:
        'HireSort gives growing teams a more structured way to manage recruitment from job description to shortlist.',
    },
    {
      type: 'positioning',
      eyebrow: 'Positioning',
      title: 'Recruitment Software Built Around the First Real Hiring Bottleneck: Screening Resumes.',
      body: [
        'Many recruitment tools focus on the entire hiring process: job posting, sourcing, scheduling, messaging, approvals, offers, onboarding, and reporting.',
        'HireSort focuses on the part where many teams struggle first:',
      ],
      quote: 'Turning a large pile of resumes into a clear, reviewable shortlist.',
    },
    {
      type: 'paragraph',
      eyebrow: 'Search intent',
      title: 'For Teams Searching for Candidate Screening Software, Not Another Bloated HR Suite.',
      body: [
        'Many teams looking for recruitment software are really trying to solve a narrower problem: too many applicants, too many resumes, and no consistent way to decide who should be reviewed first.',
        'HireSort is built for that workflow. It helps hiring teams screen resumes, rank candidates, explain why someone is a fit, and move shortlisted candidates into a lightweight pipeline.',
        'That makes it useful for lean recruiting teams, hiring managers, startups, and agencies that need candidate screening software before they need a full enterprise HR system.',
      ],
    },
    {
      type: 'paragraph',
      eyebrow: 'Who it is for',
      title: 'AI Recruitment Software for Lean Teams, Agencies, and High-Volume Hiring.',
      body: [
        'HireSort is a fit when your recruiting team needs screening speed before it needs a heavy recruiting operations suite. It is especially useful for startups hiring their first teams, agencies reviewing large candidate batches, and hiring managers who need clearer shortlist recommendations.',
        'For US and UK hiring teams, the workflow is designed around human-reviewed AI screening: recruiters can review the evidence, adjust context, and decide who moves forward instead of relying on black-box automation.',
        'For high-volume hiring, HireSort helps recruiters prioritize which resumes deserve attention first, then keeps candidate records reusable for future openings.',
      ],
    },
    {
      type: 'workflow',
      eyebrow: 'How it works',
      title: 'From Job Description to Shortlist in a Simple Workflow.',
      intro:
        'Create job → Generate rubric → Upload resumes → AI screens candidates → Review shortlist → Track stages → Reuse resumes',
      steps: [
        { n: '01', title: 'Create a job', body: 'Paste your job description or upload a JD file. HireSort uses the role requirements as the foundation for screening.' },
        { n: '02', title: 'Generate a role-specific screening rubric', body: 'HireSort creates a structured rubric from the job description. Recruiters can review and adjust the criteria before resumes are screened.' },
        { n: '03', title: 'Upload resumes in bulk', body: 'Upload resumes in PDF or DOCX format. HireSort parses each resume and extracts key candidate details.' },
        { n: '04', title: 'Screen candidates with AI', body: 'Candidates are evaluated against the role-specific rubric, not just keywords. Each candidate receives a score, breakdown, and explanation.' },
        { n: '05', title: 'Review ranked shortlists', body: 'See candidates ranked by role fit, with strengths, missing elements, score breakdowns, and evidence from the resume.' },
        { n: '06', title: 'Track candidate progress', body: 'Move candidates across simple hiring stages such as New, Shortlisted, Round 1, Offer Made, Hired, Rejected, or On Hold.' },
        { n: '07', title: 'Reuse resumes for future roles', body: 'Store uploaded resumes in a central repository so candidates can be considered again for future jobs.' },
      ],
    },
    {
      type: 'features',
      eyebrow: 'Features',
      title: 'Everything Growing Teams Need to Organize Early-Stage Hiring.',
      items: [
        { icon: 'sparkles', title: 'AI resume screening', body: 'Screen candidates against job-specific criteria instead of manually reading every resume from scratch.' },
        { icon: 'clipboardCheck', title: 'Rubric-first evaluation', body: 'Create structured hiring criteria from the job description and apply the same standard across every candidate.' },
        { icon: 'listChecks', title: 'Ranked candidate shortlists', body: 'Quickly identify which candidates should be reviewed first.' },
        { icon: 'fileSearch', title: 'Explainable candidate scoring', body: 'See why a candidate was scored highly or poorly using evidence, score breakdowns, strengths, and missing elements.' },
        { icon: 'fileScan', title: 'Resume parsing', body: 'Extract key candidate details such as name, email, phone number, current role, company, skills, and experience.' },
        { icon: 'database', title: 'Central resume repository', body: 'Store resumes in one reusable candidate library instead of treating every upload as a one-time screening event.' },
        { icon: 'ganttChart', title: 'Candidate stage tracking', body: 'Track what happens after screening with simple stage movement.' },
        { icon: 'search', title: 'Search and filtering', body: 'Find candidates by name, role, stage, score range, or date added.' },
        { icon: 'fileText', title: 'Candidate detail view', body: 'Review resume preview, parsed metadata, role association, score, and current stage in one place.' },
        { icon: 'refreshCcw', title: 'Resume reuse', body: 'Attach existing candidates to new jobs and screen them again for future roles.' },
      ],
    },
    {
      type: 'fieldList',
      eyebrow: 'Candidate management',
      title: 'Build a Reusable Candidate Database.',
      intro:
        'HireSort is designed to help recruiters manage resumes beyond a single screening workflow. Every uploaded resume can become a reusable candidate record with:',
      cardLabel: 'Candidate record',
      cardIcon: 'userSearch',
      fields: [
        'Candidate name',
        'Email',
        'Phone number',
        'Current role',
        'Current company',
        'Key skills',
        'Years of experience',
        'Date added',
        'Source of upload',
        'Role or JD association',
        'Latest screening score',
        'Current candidate stage',
      ],
    },
    {
      type: 'fieldList',
      eyebrow: 'Collaboration',
      title: 'Help Recruiters and Hiring Managers Align Faster.',
      intro:
        'Hiring slows down when recruiters and hiring managers evaluate candidates differently. HireSort makes the process more structured by giving both sides a shared view of:',
      cardLabel: 'Shared context',
      cardIcon: 'users',
      fields: [
        'What the role requires',
        'Which criteria are being used',
        'How candidates were scored',
        'Why a candidate was shortlisted',
        'What evidence supports the score',
        'Where the candidate stands in the process',
      ],
      closing:
        'Instead of debating vague resume impressions, teams can discuss candidates using a common scoring framework.',
    },
    {
      type: 'useCases',
      eyebrow: 'Use cases',
      title: 'Built for Practical Recruiting Workflows.',
      items: [
        { icon: 'users', title: 'For recruiters', body: 'Reduce manual screening time and create stronger shortlists for hiring managers.' },
        { icon: 'building', title: 'For founders', body: 'Move beyond inbox-based hiring and create a structured process for your first few roles.' },
        { icon: 'clipboardCheck', title: 'For hiring managers', body: 'Define what good looks like and review candidates scored against your actual criteria.' },
        { icon: 'handCoins', title: 'For recruitment agencies', body: 'Process high-volume resume batches and reuse strong candidates across multiple client requirements.' },
        { icon: 'rocket', title: 'For small teams', body: 'Get the core structure of recruitment software without heavy setup, complex workflows, or enterprise overhead.' },
        { icon: 'search', title: 'For US hiring teams', body: 'Use AI-assisted resume screening with recruiter review, evidence, and audit-friendly shortlist context.' },
      ],
    },
    {
      type: 'comparison',
      eyebrow: 'Comparison',
      title: 'HireSort vs Spreadsheets, Email, and Traditional Recruitment Software.',
      columns: ['Capability', 'Spreadsheets / Email', 'Traditional Recruitment Software', 'HireSort'],
      accentColIndex: 3,
      rows: [
        ['Resume storage', 'Scattered', 'Centralized', 'Centralized and reusable'],
        ['Resume screening', 'Manual', 'Often manual or keyword-based', 'AI-assisted and rubric-based'],
        ['Candidate ranking', 'Manual', 'Varies', 'Built around ranked shortlists'],
        ['Candidate tracking', 'Manual updates', 'Full workflow tracking', 'Lightweight stage tracking'],
        ['Candidate reuse', 'Difficult', 'Usually available', 'Core repository workflow'],
        ['Screening explanations', 'No', 'Limited', 'Evidence-based scoring'],
        ['Setup effort', 'Low but messy', 'Often higher', 'Lightweight'],
        ['Best first use case', 'Ad hoc tracking', 'Full recruiting operations', 'AI resume screening and candidate shortlisting'],
        ['Human review', 'Manual and inconsistent', 'Depends on workflow design', 'Recruiter-reviewed AI scores and resume evidence'],
        ['Best fit', 'Very early hiring', 'Mature hiring teams', 'Growing teams that need faster screening and cleaner candidate management'],
      ],
    },
    {
      type: 'comparison',
      eyebrow: 'Use-case fit',
      title: 'Which Recruitment Software Workflow Fits Your Team?',
      columns: ['Team type', 'Primary pain', 'What to prioritize', 'Where HireSort fits'],
      accentColIndex: 3,
      rows: [
        ['Startup hiring team', 'Founders and managers screen resumes manually', 'Fast setup, clear shortlists, low overhead', 'AI screening plus lightweight tracking before a full ATS is needed'],
        ['Recruitment agency', 'Large candidate batches across client roles', 'Reusable candidate records and ranked review order', 'Resume repository, candidate reuse, and evidence-backed recommendations'],
        ['High-volume hiring team', 'Too many applicants for manual review', 'Bulk resume screening and shortlist prioritization', 'Role-specific scoring and ranked candidates for faster review'],
        ['Hiring manager-led process', 'Shortlists are inconsistent or hard to explain', 'Shared criteria and clear evidence', 'Rubric-first screening with strengths, gaps, and score context'],
        ['US hiring team', 'AI needs reviewability and practical controls', 'Human oversight, evidence, and privacy expectations', 'Human-reviewed AI screening rather than automated rejection'],
      ],
    },
    {
      type: 'why',
      eyebrow: 'Why HireSort',
      title: 'Why Teams Choose HireSort Recruitment Software.',
      items: [
        { title: 'Faster shortlisting', body: 'Move from hours of resume review to structured candidate rankings.' },
        { title: 'Better hiring consistency', body: 'Use the same role-specific rubric for every candidate.' },
        { title: 'Cleaner candidate organization', body: 'Keep resumes, scores, role associations, and stages in one workspace.' },
        { title: 'Less spreadsheet dependency', body: 'Replace manual trackers with simple candidate management.' },
        { title: 'Better candidate reuse', body: 'Build a searchable resume repository that becomes more valuable over time.' },
        { title: 'More explainable decisions', body: 'Review evidence and scoring logic instead of relying only on memory or instinct.' },
      ],
    },
    {
      type: 'plansSplit',
      eyebrow: 'Plans',
      title: 'Useful From Day One. More Powerful as Your Hiring Grows.',
      free: {
        label: 'Free / MVP',
        heading: 'Practical day-to-day recruiting.',
        bullets: [
          'Central resume repository',
          'Candidate metadata extraction',
          'Resume-to-role association',
          'Resume reuse for future screening',
          'Basic search and filtering',
          'Manual stage movement',
          'Basic funnel customization',
          'Candidate detail page with score and stage',
        ],
      },
      paid: {
        label: 'Paid / Expanded',
        heading: 'Deeper recruitment operations.',
        bullets: [
          'Saved talent pools',
          'Saved filters and searches',
          'Advanced filtering',
          'CSV export',
          'Candidate notes',
          'Recruiter comments',
          'Collaboration workflows',
          'Advanced repository search',
          'Custom candidate table columns',
          'Kanban board',
          'Bulk stage movement',
          'Multiple funnel templates',
          'Deeper candidate history',
        ],
      },
    },
    {
      type: 'scope',
      eyebrow: 'Scope clarity',
      title: 'Recruitment Software Focused on Screening and Candidate Management.',
      inLabel: 'Focused on',
      inItems: [
        'Resume screening',
        'Candidate ranking',
        'Resume management',
        'Candidate tracking',
        'Search and filtering',
        'Role-based evaluation',
        'Candidate reuse',
      ],
      outLabel: 'Not in near-term scope',
      outItems: [
        'Interview scheduling',
        'Offer letters',
        'Candidate messaging',
        'Background checks',
        'Onboarding',
        'Full HR workflows',
      ],
    },
  ],

  cta: {
    eyebrow: 'Ready when you are',
    title: 'Ready to make recruiting more structured?',
    body: 'Use HireSort to screen resumes faster, manage candidate records, track hiring stages, and build better shortlists.',
    primary: { label: 'Get started for free', href: redirectURL },
    secondary: { label: 'View pricing', href: '/pricing' },
  },

  faqs: [
    { id: 'what-is', question: 'What Is Recruitment Software?', answer: ['Recruitment software helps hiring teams manage parts of the hiring process, such as collecting resumes, tracking candidates, screening applications, managing shortlists, and coordinating hiring decisions.'] },
    { id: 'ai-recruitment-software', question: 'What Is AI Recruitment Software for Resume Screening?', answer: ['AI recruitment software for resume screening uses AI to compare resumes against a role, identify stronger-fit candidates, explain scoring decisions, and help recruiters build shortlists faster.'] },
    { id: 'candidate-screening-software', question: 'Is HireSort Candidate Screening Software?', answer: ['Yes. HireSort is candidate screening software focused on the resume review stage. It helps teams screen applicants, rank candidates, review evidence, and move shortlisted profiles into a lightweight hiring pipeline.'] },
    { id: 'high-volume', question: 'Can HireSort Support High-Volume Hiring?', answer: ['Yes. HireSort is designed for bulk resume uploads and ranked shortlists, which makes it useful for high-volume hiring workflows where recruiters need to review many applicants quickly.'] },
    { id: 'how-different', question: 'How Is HireSort Different From Traditional Recruitment Software?', answer: ['HireSort is focused on AI resume screening and lightweight candidate management. Instead of trying to manage every hiring workflow, it helps teams solve the first major bottleneck: turning resumes into structured shortlists.'] },
    { id: 'is-ats', question: 'Is HireSort an ATS?', answer: ['HireSort can act as a lightweight ATS for teams that need resume management, candidate tracking, and screening-first workflows. It is not currently positioned as a full enterprise ATS.'] },
    { id: 'ai-screening', question: 'Does HireSort Support AI Resume Screening?', answer: ['Yes. HireSort screens resumes against job-specific rubrics and produces ranked shortlists with score breakdowns and explanations.'] },
    { id: 'replace-spreadsheets', question: 'Can HireSort Replace Spreadsheets?', answer: ['Yes. HireSort is designed to reduce dependence on spreadsheets by giving teams a central place to store resumes, view candidate data, track stages, and reuse candidate records.'] },
    { id: 'reuse-candidates', question: 'Can I Reuse Candidates for Future Roles?', answer: ['Yes. HireSort’s resume management layer is designed to store candidates in a central repository so they can be mapped to future jobs and screened again.'] },
    { id: 'best-for', question: 'Who Is HireSort Best For?', answer: ['HireSort is best for recruiters, founders, hiring managers, small teams, and recruitment agencies that need faster resume screening and simpler candidate tracking.'] },
    { id: 'startup-agency', question: 'Is HireSort Useful for Startups and Staffing Agencies?', answer: ['Yes. Startups can use HireSort to create a structured screening workflow before buying a heavy recruiting suite. Staffing agencies can use it to review large resume batches, reuse candidate records, and produce clearer shortlist recommendations for client roles.'] },
    { id: 'us-teams', question: 'Can US Hiring Teams Use AI Recruitment Software Safely?', answer: ['US hiring teams should use AI recruitment software with human review, clear evidence, and practical oversight. HireSort is positioned as a recruiter-reviewed screening workflow, not a black-box automated rejection system.'] },
    { id: 'scheduling-offers', question: 'Does HireSort Include Interview Scheduling and Offer Management?', answer: ['No. Those workflows are outside the near-term scope. HireSort is focused on resume screening, candidate management, stage tracking, and shortlist creation.'] },
  ],

  internalLinks: [
    { href: '/product/applicant-tracking-system', label: 'Applicant Tracking System' },
    { href: '/resources/best/candidate-screening-software', label: 'Best Candidate Screening Software' },
    { href: '/resources/best/high-volume-hiring-software', label: 'High-Volume Hiring Software' },
    { href: '/resources/best/ai-resume-screening-software', label: 'Best AI Resume Screening Software' },
    { href: '/resources/compare/hiresort-vs-manual-screening', label: 'HireSort vs Manual Screening' },
    { href: '/resources/compare/ai-resume-screening-vs-ats', label: 'AI Resume Screening vs ATS' },
    { href: '/blog/resume-screening-checklist', label: 'Resume Screening Checklist' },
    { href: '/blog/how-to-shortlist-candidates-faster', label: 'How to Shortlist Candidates Faster' },
    { href: '/blog/ai-resume-screening-tool', label: 'AI Resume Screening Tool' },
    { href: '/blog/candidate-scorecard-template', label: 'Candidate Scorecard Template' },
    { href: '/product/resume-parser', label: 'Resume Screening Software' },
    { href: '/product/resume-management', label: 'Resume Management' },
    { href: '/product/candidate-pipeline', label: 'Candidate Pipeline' },
    { href: '/resources/compare/workable-alternative', label: 'Workable Alternative' },
    { href: '/pricing', label: 'Pricing' },
  ],
};
